### PR TITLE
removed non flash code because event capture was not implemented.

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl-robotlegs-framework/1)

### CODE REVIEW

**Comment by crazyjul** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/robotlegs/bender/extensions/viewManager/impl/StageObserver.hx, line 98 [r1]](https://reviewable.io:443/reviews/fishingcactus/openfl-robotlegs-framework/1#-KQdeK0UVP-8gBvfTrfO:-KQdeK0UVP-8gBvfTrfP:bpkvxq1) ([raw file](https://github.com/fishingcactus/openfl-robotlegs-framework/blob/07f94cf02f649a4de65783b9e634c38fa8e1375f/src/robotlegs/bender/extensions/viewManager/impl/StageObserver.hx#L98)):_

> ``` Haxe
>               //traver.childRemoved.remove(OnChildRemoved);
>           }
>           traver = new DisplaylistTraverser(container);
> ```

If `DisplayListTraverser` is not used anymore, it should be deleted 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl-robotlegs-framework/1)_

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl-robotlegs-framework/1)_

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/robotlegs/bender/extensions/viewManager/impl/StageObserver.hx, line 98 [r1]](https://reviewable.io:443/reviews/fishingcactus/openfl-robotlegs-framework/1#-KQdeK0UVP-8gBvfTrfO:-KQekyGFaYcMsDTtVVM4:b-896fix) ([raw file](https://github.com/fishingcactus/openfl-robotlegs-framework/blob/07f94cf02f649a4de65783b9e634c38fa8e1375f/src/robotlegs/bender/extensions/viewManager/impl/StageObserver.hx#L98)):_
<details><summary>

<i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary>



> If `DisplayListTraverser` is not used anymore, it should be deleted 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl-robotlegs-framework/1)_

**Comment by crazyjul** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl-robotlegs-framework/1)_

**Pull request merged**
